project:
  type: website

website:
  title: "Dr Johan Ibrahim"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: 
    left: "Copyright 2024, Dr Johan Ibrahim"
    center: "Made with ❤️ and Quarto"
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/
      
  navbar:
    search: true
    right: 
      - text: Talks
        href: talks/index.qmd
        icon: megaphone
      - text: Blog
        href: blog/index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: "{{< iconify ai google-scholar >}}"
        href: https://scholar.google.com/
    tools:
      - icon: github
        href: github.com
      
format:
  html:
    theme: [cosmo, styles.scss]

