project:
  type: website

website:
  title: "Dr Johan Ibrahim"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: 
    left: "Copyright 2024, Dr Johan Ibrahim"
    center: "Made with ❤️ and Quarto"
    right:
      - text: "{{< iconify fa6-brands github >}}"
        href: "https://github.com/DrJohan"
      - text: "{{< iconify fa6-brands twitter >}}"
        href: "https://twitter.com/DrJohan81"
      
  navbar:
    search: true
    right: 
      - text: Talks
        href: talks/index.qmd
        icon: megaphone
      - text: Blog
        href: blog/index.qmd
        icon: substack
      - text: Projects
        icon: kanban
        href: projects/index.qmd
    tools:
      - icon: twitter
        href: "https://twitter.com/DrJohan81"
      - icon: github
        href: "https://github.com/DrJohan"
      
    
format:
  html:
    theme: [cosmo, styles.scss]

